Advanced:
  exhaustiveness: 512
  randomize: true
  mc_steps: 20
  opt_steps: -1
  tor_prec: 0.3
  box_prec: 1.0
  refine_steps: 5
  num_pose: 10
  rmsd_limit: 1.0
  energy_range: 3.0
  seed: 12345
  use_tor_lib: false
Hardware:
  gpu_device_id: 0
Settings:
  size_x: 30.0
  size_y: 30.0
  size_z: 30.0
  task: screen
  search_mode: balance
Preprocessing:
  template_docking: true
  reference_sdf_file_name: reference.sdf
  core_atom_mapping_dict_list: null
  covalent_ligand: false
  covalent_residue_atom_info_list: null
  preserve_receptor_hydrogen: false
  remove_temp_files: true
  working_dir_name: .
