{% set name = "unidock2" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version").split(".")[0] | int %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}
  # skip: true

requirements:
  build:
    # - python
    # - cross-python_{{ target_platform }}
    # - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} # [(linux or win) and cuda_compiler != "None"]
    # - cuda-version {{ cuda_compiler_version }} # [(cuda_compiler_version or "None") != "None"]
    - cmake =3.27
    - make
    - pybind11

  host:
    - python
    - pip
    - scikit-build-core >=0.2.0
    # - cython
    - setuptools
    - cuda-version {{ cuda_compiler_version }} # [(cuda_compiler_version or "None") != "None"]
    {% if cuda_compiler_version != "None" %}
    - libcurand-dev
    - cuda-cudart-dev
    - cuda-driver-dev  # [linux]
    {% endif %}
  run:
    - pyyaml
    - pathos
    - numpy
    - scipy
    - pandas
    - networkx
    - rdkit
    - mdanalysis
    - openbabel
    - pdbfixer
    - openmm
    - msys_viparr_lpsolve55
    - ambertools_stable

test:
  imports:
    - unidock_engine
    - unidock_processing
